# Generated by Django 3.0 on 2020-04-12 20:02

from django.db import migrations

def create_data(apps, schema_editor):
    Note = apps.get_model('simple_app', 'Note')
    Note(name="add a note", deadlineDate="01.04.2020").save()


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
